module.exports = {
    register: require('./register'),
    authenticateUser: require('./authenticate-user'),
    retrieveUser: require('./retrieve-user'),
    createSession: require('./create-session'),
    updateSession: require('./update-session'),
    retrieveSession: require('./retrieve-session'),
    removeSession: require('./remove-session'),
    addContact: require('./add-contact'),
    searchContacts: require('./search-contacts'),
    deleteContact: require('./delete-contact'),
    updateUser: require('./update-user'),
    addSticky: require('./add-sticky'),
    updateContact: require('./update-contact'),
    searchStickies: require('./search-stickies'),
}