const names=[//Para la generación aleatoria de nombres
    "Juan",
    "Pedro",
    "Miguel",
    "Luis",
    "Guillermo",
    "Alfonso",
    "Alfredo",
    "Jacinto",
    "Pablo",
    "Francisco",
    "Maria",
    "Helena",
    "Naomi",
    "Marta",
    "Juliana",
    "Valeria",
    "Susana",
    "Noelia",
    "Pilar",
    "Raquel",
    "Josefa"
];
const surnames=[
    "Gracia",
    "Gonzalez",
    "Rodriguez",
    "Sanchez",
    "Arriazu",
    "Gochicoa",
    "Vela",
    "Bozal",
    "Santos",
    "Ruiz",
    "Urrutia",
    "Fernandez",
    "Rubio",
    "Chueca"
];
const passwords=[
    "123456789",
    "contraseña123",
    "123contraseña",
    "incorrectajajaxd1",
    "DosPutosPepinillos"
];