
module.exports = {
    registerUser: require('./register-user'),
    authenticateUser: require('./authenticate-user'),
    retrieveUser: require('./retrieve-user'),
    addMemberDepartment: require('./add-member-department'),
    addPetition: require('./add-petition'),
    createDepartment: require('./create-department'),
    createMeeting: require('./create-meeting'),
    createSummary: require('./create-summary'),
    createWorkGroup:require('./create-work-group'),
    retrieveDepartments: require('./retrieve-departments'),
    retrieveAllPetitions:require('./retrieve-all-petitions'),
    retrieveWorkGroups:require('./retrieve-work-groups'),
    searchUser: require('./search-users'),
    searchWorkGroups: require('./search-work-groups'),
    updatePetition: require('./update-petition'),
    updateSummary: require('./update-summary'),
    retrieveWorkGroupPref: require('./retrieve-work-group-pref'),
    changeWorkGroup: require('./change-work-group-pref'),
    addReadBy: require('./add-read-by'),
    retrieveReadBy: require('./retrieve-read-by'),
    retrieveMeetings: require('./retrieve-meetings'),
    retrieveDepartMembers: require('./retrieve-depart-members'),
    retrieveSummaries: require('./retrieve-summaries'),
    retrieveSummarys: require('./retrieve-summarys'),
    retrieveWorkGroup: require('./retrieve-work-group'),
    addMemberSummary: require('./add-member-summary'),
    addDepartmentSummary: require('./add-departmembers-summary'),
    retrieveSummaryMembers: require('./retrieve-summary-members')
}