const playersTop = [
    'Messi',
    'Cristiano Ronaldo',
    'Neymar Jr.',
    'Hazard',
    'Kevin de Bruyne',
    'Oblak',
    'Van Dijk',
    'Mohamed Salah',
    'Modrić',
    'Ter Stegen',
    'Mbappé',
    'Sergio Ramos',
    'Sergio Agüero',
    'Chiellini',
    'Lewandowski',
    'Kane',
    'Kalidou Koulibaly',
    'Golo Kanté',
    'Alisson',  
    'Griezmann', 
    'Sergio Busquets',  
    'Luis Suárez',  
    'De Gea', 
    'Raheem Sterling',  
    'Aubameyang',  
    'Gerard Piqué',  
    'Neuer',  
    'Mané',  
    'Kroos', 
    'Eriksen',  
    'Pogba', 
    'Cavani',  
    'Marco Reus',  
    'Ederson',
    'David Silva', 
    'Hugo Lloris', 
    'Godín',
    'Dybala', 
    'Courtois',
    'Samir Handanovič',
    'Benzema',
    'Jordi Alba',
    'Mats Hummels',
    'Fernandinho', 
    'Heung Min Son',
    'Toby Alderweireld',
    'Bernardo Silva',
    'Thiago',
    'Aymeric Laporte',
    'Dries Mertens',
    'Thiago Silva',
    'Casemiro',
    'Lorenzo Insigne',
    'Jan Vertonghen',
    'Keylor Navas',
    'Joshua Kimmich',
    'Leroy Sané',
    'Pjanić',
    'Di María',
    'Alexandre Lacazette',
    'Marquinhos',
    'Firmino',
    'Marco Verratti',
    'Leonardo Bonucci',
    'Rakitić',
    'Milan Škriniar',
    'Samuel Umtiti',
    'Thomas Müller',
    'Coutinho',
    'Ciro Immobile',
    'Isco',
    'Wojciech Szczęsny',
    'Daniel Parejo',
    'Marcelo',
    'Gianluigi Donnarumma',
    'James Rodríguez',
    'Frenkie de Jong',
    'Varane',
    'Andrew Robertson',
    'Axel Witsel',
    'De Ligt', 
    'Fabinho', 
    'Alex Sandro', 
    'Niklas Süle', 
    'Alejandro Gómez', 
    'Romelu Lukaku', 
    'Blaise Matuidi',
    'David Alaba',
    'Dani Carvajal',
    'Mauro Icardi',
    'Koke',
    'Kostas Manolas',
    'José María Giménez',
    'Sergej Milinkovi',
    'Rodri',
    'Allan',
    'Hakim Ziyech',
    'Saúl',
    'Bruno Fernandes',
    'Zlatan Ibrahimović',
]