const playersTop = [
    'Messi',
    'Cristiano Ronaldo',
    'Neymar Jr',
    'Hazard',
    'Kevin de Bruyne',
    'Oblak',
    'Van Dijk',
    'Mohamed Salah',
    'Modric',
    'Ter Stegen',
    'Mbappe',
    'Sergio Ramos',
    'Sergio Agüero',
    'Chiellini',
    'Lewandowski',
    'Kane',
    'Kalidou Koulibaly',
    'Golo Kante',
    'Alisson',  
    'Griezmann', 
    'Sergio Busquets',  
    'Luis Suarez',  
    'De Gea', 
    'Raheem Sterling',  
    'Aubameyang',  
    'Gerard Piqué',  
    'Neuer',  
    'Mane',  
    'Kroos', 
    'Eriksen',  
    'Pogba', 
    'Cavani',  
    'Marco Reus',  
    'Ederson',
    'David Silva', 
    'Hugo Lloris', 
    'Godin',
    'Dybala', 
    'Courtois',
    'Samir Handanovic',
    'Benzema',
    'Jordi Alba',
    'Mats Hummels',
    'Fernandinho', 
    'Heung Min Son',
    'Toby Alderweireld',
    'Bernardo Silva',
    'Thiago',
    'Aymeric Laporte',
    'Dries Mertens',
    'Thiago Silva',
    'Casemiro',
    'Lorenzo Insigne',
    'Jan Vertonghen',
    'Keylor Navas',
    'Joshua Kimmich',
    'Leroy Sane',
    'Pjanic',
    'Di Maria',
    'Alexandre Lacazette',
    'Marquinhos',
    'Firmino',
    'Marco Verratti',
    'Leonardo Bonucci',
    'Rakitic',
    'Milan Skriniar',
    'Samuel Umtiti',
    'Thomas Muller',
    'Coutinho',
    'Ciro Immobile',
    'Isco',
    'Wojciech Szczęsny',
    'Daniel Parejo',
    'Marcelo',
    'Gianluigi Donnarumma',
    'James Rodríguez',
    'Frenkie de Jong',
    'Varane',
    'Andrew Robertson',
    'Axel Witsel',
    'Fabinho', 
    'Alex Sandro', 
    'Niklas Sule', 
    'Alejandro Gomez', 
    'Romelu Lukaku', 
    'Blaise Matuidi',
    'David Alaba',
    'Dani Carvajal',
    'Mauro Icardi',
    'Koke',
    'Kostas Manolas',
    'Jose María Giménez',
    'Sergej Milinkovi',
    'Rodri',
    'Allan',
    'Hakim Ziyech',
    'Saul',
    'Bruno Fernandes',
    'Zlatan Ibrahimovic',
]