module.exports = {
    Landing: require('./Landing'),
    Login: require('./Login'),
    Register: require('./Register'),
    ButtonForm: require('./ButtonForm'),
    WellcomePage: require('./WellcomePage'),
    UpdateUser: require('./UpdateUser'),
    JoinCommunity: require('./JoinCommunity'),
    CreateCommunity: require('./CreateCommunity'),
    Home: require('./Home'),
    Chat: require('./Chat'),
    HeaderHome: require('./HeaderHome'),
    Laundry: require('./Laundry/'),
    ShopList: require('./ShopList'),
    ShopListAdmin: require('./ShopListAdmin'),
    WeekDays: require('./Laundry/'),
    TimeLaundry: require('./Laundry/'),
    SingleFruit: require('./SingleFruit'),
    InfoCommunity: require('./InfoCommunity'),
    InfoCommunityAdmin: require('./InfoCommunity')
}