const {expect}= require("chai")
const Rounder= require("./rounder")

describe("Rounder",()=>{
    it("should round a number into an integer",()=>{
        expect(Rounder.round(1)).to.equal(1)
        expect(Rounder.round(1.1)).to.equal(1)
        expect(Rounder.round(1.22)).to.equal(1)
        expect(Rounder.round(1.333)).to.equal(1)
        expect(Rounder.round(1.4444)).to.equal(1)
        expect(Rounder.round(1.5)).to.equal(2)
        expect(Rounder.round(1.66)).to.equal(2)
        expect(Rounder.round(1.777)).to.equal(2)
        expect(Rounder.round(1.8888)).to.equal(2)
        expect(Rounder.round(1.99999)).to.equal(2)
        expect(Rounder.round(2)).to.equal(2)
    })
    it("should round a number to the specified amount of decimals",()=>{
        expect(Rounder.round(1.23456789,0)).to.equal(1)
        expect(Rounder.round(1.23456789,1)).to.equal(1.2)
        expect(Rounder.round(1.23456789,2)).to.equal(1.23)
        expect(Rounder.round(1.23456789,3)).to.equal(1.235)
        expect(Rounder.round(1.23456789,4)).to.equal(1.2346)
        expect(Rounder.round(1.23456789,5)).to.equal(1.23457)
        expect(Rounder.round(1.23456789,6)).to.equal(1.234568)
        expect(Rounder.round(1.23456789,7)).to.equal(1.2345679)
        expect(Rounder.round(1.23456789,8)).to.equal(1.234567890)
    })
    it("should throw an error when not given the base number",()=>{
        expect(()=>{Rounder.round()}).to.throw(TypeError,"undefined is not a number")
        expect(()=>{Rounder.round(undefined,2)}).to.throw(TypeError,"undefined is not a number")
    })
    it("should throw an error wen given parameters that are not numbers",()=>{
        expect(()=>{Rounder.round("string")}).to.throw(TypeError,"string is not a number")
        expect(()=>{Rounder.round([])}).to.throw(TypeError," is not a number")
        expect(()=>{Rounder.round({})}).to.throw(TypeError,"[object Object] is not a number")
        expect(()=>{Rounder.round(true)}).to.throw(TypeError,"true is not a number")
        expect(()=>{Rounder.round(()=>{})}).to.throw(TypeError,"()=>{} is not a number")

        expect(()=>{Rounder.round(1,"string")}).to.throw(TypeError,"string is not a number")
        expect(()=>{Rounder.round(1,[])}).to.throw(TypeError," is not a number")
        expect(()=>{Rounder.round(1,{})}).to.throw(TypeError,"[object Object] is not a number")
        expect(()=>{Rounder.round(1,true)}).to.throw(TypeError,"true is not a number")
        expect(()=>{Rounder.round(1,()=>{})}).to.throw(TypeError,"()=>{} is not a number")
    })
})